apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventario-app-green
  labels:
    app: inventario-app
    version: green
spec:
  replicas: 3
  selector:
    matchLabels:
      app: inventario-app
      version: green
  template:
    metadata:
      labels:
        app: inventario-app
        version: green
    spec:
      containers:
        - name: app
          image: inventario-app-final:test
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
          env:
            - name: APP_COLOR
              value: "green"
            - name: STARTUP_DELAY_SECONDS
              value: "15"
            - name: API_KEY
              valueFrom:
                secretKeyRef:
                  name: inventario-secret
                  key: API_KEY
          readinessProbe:
            httpGet: { path: /health, port: 3000 }
            initialDelaySeconds: 2
            periodSeconds: 3
          livenessProbe:
            httpGet: { path: /health, port: 3000 }
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "200m"
              memory: "128Mi"