apiVersion: v1
kind: Service
metadata:
  name: inventario-app-bluegreen
spec:
  type: NodePort
  selector:
    app: inventario-app
    version: blue   # <-- cambiar a "green" para cortar tráfico
  ports:
    - port: 80
      targetPort: 3000